# Generated by Django 5.2.3 on 2025-06-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="コンテンツタイトル"),
                ),
                ("content", models.TextField(verbose_name="コンテンツ内容")),
                ("category", models.CharField(max_length=100, verbose_name="カテゴリ")),
                (
                    "tags",
                    models.TextField(blank=True, verbose_name="タグ（カンマ区切り）"),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="公開済み"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="閲覧数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "ウェブコンテンツ",
                "verbose_name_plural": "ウェブコンテンツ",
                "ordering": ["-created_at"],
            },
        ),
    ]
